# -*- mode: ruby -*-
# vi: set ft=ruby :

#name of vm to current directory
vm_prefix = "chefmama2"
#number of vms
vm_number = 1

Vagrant.configure("2") do |config|
  config.vm.box = "vsphere-dummy"

  (1..vm_number).each do |i|
    config.vm.define vm_name = "#{vm_prefix}%01d" % i do |config|
      config.vm.hostname = vm_name
      config.vm.provider :vsphere do |vsphere|
        vsphere.name = vm_name
        vsphere.compute_resource_name = 'CLUSTER_INTDEV_QA_UAT_PREPROD'
        vsphere.template_name = 'Templates/vTemplate-Ubuntu17'
        vsphere.linked_clone = false
        vsphere.customization_spec_name = 'spec_linux'
        vsphere.vlan = 'INTDEV_VLAN10'
        vsphere.host = 'vcenterdevo.collegemultihexa.ca'
        vsphere.insecure = true
        vsphere.user = 'administrator@vsphere.local'
        vsphere.password = 'P@ssw0rd'
      end
    end
  end
end

